AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 IAM role template
Parameters:
  RealmName:
    Description: "The name of this realm"
    Type: "String"
    MinLength: "0"
    MaxLength: "34"
  Bucketname:
    Description: "The name of the s3 bucket"
    Type: "String"
    MinLength: "2"
    MaxLength: "34"  
  Vaultname:
    Description: "The name of the vault to be access"
    Type: "String"
    MinLength: "0"
    MaxLength: "34"
  AccountId:
    Description: "The name of this account"
    Type: "String"
    MinLength: "0"
    MaxLength: "24"
    AllowedPattern: "[0-9]*"
  Region:
    Description: "The name of the data source to be access"
    Type: "String"
    MinLength: "0"
    MaxLength: "34"

Resources:
    S3AWSBatchRetrieveRole:
      Type: "AWS::IAM::Role"
      Properties:
        Description: " Allows S3 to call AWS services on your behalf."
        RoleName:
          !Join [ "", ["AwsS3BatchRetrieveAccess", !Ref RealmName]]
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: AllowUserToReadS3Object
            Effect: Allow
            Principal:
              Service:
                cloudformation.amazonaws.com
            Action: 
            - sts:AssumeRole
        Path : "/"
     
    S3RolePolicies: 
      Type: "AWS::IAM::Policy"
      Properties: 
        PolicyName: "S3FullAccess"
        PolicyDocument:   
          Version: "2012-10-17"
          Statement: 
            - Effect: "Allow"
              Action: 
                - "s3:GetObject"
                - s3:PutObject
              Resource:
                - !Join [ "", ["arn:aws:s3:::", !Ref Bucketname]] 
                - !Join [ "", ["arn:aws:s3:*:*:accesspoint/*"]]
                - !Join [ "", ["arn:aws:s3:::*/*"]]
                - !Join [ "", ["arn:aws:s3:*:*:job/*"]]
        Roles: [!Ref "S3AWSBatchRetrieveRole"]

    S3GlacierRolePolicies: 
      Type: "AWS::IAM::Policy"
      Properties: 
        PolicyName: "GlacierReadOnlyAccess"
        PolicyDocument:   
          Version: "2012-10-17"
          Statement: 
            - Effect: "Allow"
              Action:
                - "glacier:GetVaultAccessPolicy"
                - "glacier:DescribeVault"
                - "glacier:GetJobOutput"
                - "glacier:GetVaultLock"
                - "glacier:GetVaultNotifications"
                - "glacier:DescribeJob"
              Resource:
                - !Join [ "", ["arn:aws:glacier:", !Ref Region, ":", !Ref AccountId, ":vaults/", !Ref Vaultname]] 
                - !Join [ "", ["arn:aws:glacier:*:*:vaults/", !Ref Vaultname]]
            - Effect: "Allow"
              Action:
                - "glacier:GetDataRetrievalPolicy"
              Resource: "*"
        Roles: [!Ref "S3AWSBatchRetrieveRole"]